<a href="https://colab.research.google.com/github/EricVPereira/Sistemas-Lineares/blob/main/Atividade2_Sistemas_Lineares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividade 2

1.   $$ 2a - b = 5 $$
$$ 4a - 2b = 10 $$





In [1]:
import numpy as np

A = np.array([[2,-1],[4,-2]]) # matriz dos coeficientes
print(A)
B = np.array([5,10])         # termos independentes
Ax = np.array([[5,-1],[10,-2]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")

[[ 2 -1]
 [ 4 -2]]
SPI



2.   $$ -4m + 1n + 0p = 1 $$
$$ 3m + 5n - 2p = 2 $$
$$ 1m + 0n + 6p = 3 $$



In [2]:
import numpy as np

A = np.array([[-4,1,0],[3,5,-2],[1,0,6]]) # matriz dos coeficientes
print(A)
B = np.array([1,2,3])         # termos independentes
Ax = np.array([[1,1,0],[2,5,-2],[3,0,6]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")

[[-4  1  0]
 [ 3  5 -2]
 [ 1  0  6]]
SPD
[-0.08571429  0.65714286  0.51428571]



3.   $$ x + 2y +4z = 5 $$
$$ 2x - y + 2z = 8 $$
$$ 3x - 3y - z = 7 $$



In [3]:
import numpy as np

A = np.array([[1,2,4],[2,-1,2],[3,-3,-1]]) # matriz dos coeficientes
print(A)
B = np.array([5,8,7])         # termos independentes
Ax = np.array([[5,2,4],[8,-1,2],[7,-3,-1]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")

[[ 1  2  4]
 [ 2 -1  2]
 [ 3 -3 -1]]
SPD
[ 1. -2.  2.]



4.   $$ x + 2y - z = 8 $$
$$ 2x + 3y + z = 1 $$
$$ 5x + 3y - 2z = -11 $$




In [4]:
import numpy as np

A = np.array([[1,2,-1],[2,3,1],[5,3,-2]]) # matriz dos coeficientes
print(A)
B = np.array([8,1,-11])         # termos independentes
Ax = np.array([[8,2,-1],[1,3,1],[-11,3,-2]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")

[[ 1  2 -1]
 [ 2  3  1]
 [ 5  3 -2]]
SPD
[-7.  6. -3.]



5.   $$ x + y - z = 0 $$
$$ x + y + z = 200000 $$
$$ 0,15x + 0,10y + 0,06z = 20000 $$


In [5]:
import numpy as np

A = np.array([[1,1,-1],[1,1,1],[0.15,0.1,0.06]]) # matriz dos coeficientes
print(A)
B = np.array([0,200000,20000])         # termos independentes
Ax = np.array([[0,1,-1],[200000,1,1],[20000,0.1,0.06]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")

[[ 1.    1.   -1.  ]
 [ 1.    1.    1.  ]
 [ 0.15  0.1   0.06]]
SPD
[ 80000.  20000. 100000.]
