<a href="https://colab.research.google.com/github/EricVPereira/Sistemas-Lineares/blob/main/Atividade_Sistemas_Lineares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercicios
## Resolver e classificar cada sistema linear em SPD; SPI, SI
---
1.   $$  2x - y = 7 $$
$$ x + 5y = -2 $$



In [ ]:
import numpy as np

A = np.array([[2,-1],[1,5]]) # matriz dos coeficientes
print(A)
B = np.array([7,-2])         # termos independentes
Ax = np.array([[7,-1],[-2,5]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")

[[ 2 -1]
 [ 1  5]]
SPD
[ 3. -1.]


2. $$ x + 2y - z = 0 $$
$$ 3x - 4y + 5z = 10 $$
$$ x + y + 9z = 1 $$

In [ ]:
import numpy as np

A = np.array([[1,2,-1],[3,-4,5],[1,1,9]]) # matriz dos coeficientes
print(A)
B = np.array([0,10,1])         # termos independentes
Ax = np.array([[0,2,-1],[10,-4,5],[1,1,9]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")

[[ 1  2 -1]
 [ 3 -4  5]
 [ 1  1  9]]
SPD
[ 2.00000000e+00 -1.00000000e+00  4.82705663e-17]


3. $$ x + 2y = 5 $$
$$ 2x - 3y = -4 $$

In [ ]:
import numpy as np

A = np.array([[1,2],[2,-3]]) # matriz dos coeficientes
print(A)
B = np.array([5,-4])         # termos independentes
Ax = np.array([[5,2],[-4,-3]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")

[[ 1  2]
 [ 2 -3]]
SPD
[1. 2.]


4. $$ x + y = 5 $$
$$ 2x + 2y = 10 $$

In [ ]:
import numpy as np

A = np.array([[1,1],[2,2]]) # matriz dos coeficientes
print(A)
B = np.array([5,10])         # termos independentes
Ax = np.array([[5,1],[10,2]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")

[[1 1]
 [2 2]]
SPI


5. $$ 2a - b + c = 3 $$
$$ a - b + 2c = 3 $$
$$ a + b + c = 6 $$

In [ ]:
import numpy as np

A = np.array([[2,-1,1],[1,-1,2],[1,1,1]]) # matriz dos coeficientes
print(A)
B = np.array([3,3,6])         # termos independentes
Ax = np.array([[3,-1,1],[3,-1,2],[6,1,1]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")

[[ 2 -1  1]
 [ 1 -1  2]
 [ 1  1  1]]
SPD
[1.8 2.4 1.8]


6. $$ x + 4y + 7z = 2 $$
$$ 2x + 3y + 6z = 2 $$ 
$$ 5x + y - z = 8 $$

In [ ]:
import numpy as np

A = np.array([[1,4,7],[2,3,6],[5,1,-1]]) # matriz dos coeficientes
print(A)
B = np.array([2,2,8])         # termos independentes
Ax = np.array([[2,4,7],[2,3,6],[8,1,-1]])   # troca coluna x pelo termo independente
detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)

# Analisar os determinantes

if detA !=0:
  S = np.linalg.solve(A,B)
  print("SPD")
  print(S)
else:
  if detA ==0 and detAx ==0:
    print("SPI")
  else:
    print("SI")

[[ 1  4  7]
 [ 2  3  6]
 [ 5  1 -1]]
SPD
[ 1.  2. -1.]
